openapi: 3.0.1
info:
  title: Prueba API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/tasks:
    get:
      summary: Prueba para generación de código a apartir de el contrato de la API
      operationId: obtenerTareas
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/pruebaGenerarCodigo"
components:
  schemas:
    pruebaGenerarCodigo:
      type: object
      properties:
        identificador:
          type: integer
          format: int64
        titulo:
          type: string
        completado:
          type: boolean